[package]
name = "windowlab"
version = "0.1.0"
authors = ["Jan Alexandra Katz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
x11 = "2.18"
