[package]
name = "windowlab"
version = "0.1.0"
authors = ["Jan Alexandra Katz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
nix = "0.17"
xcb = { version = "0.9", features = ["render"] }
